ALTER TABLE workflows ADD COLUMN recurrent INTEGER NOT NULL DEFAULT 0;

ALTER TABLE steps ADD COLUMN recurrent INTEGER NOT NULL DEFAULT 0;

ALTER TABLE steps ADD COLUMN delay INTEGER NOT NULL DEFAULT 0;
